name: cloudspace
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.12.31=h06a4308_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - jedi=0.19.2=py310h06a4308_0
  - jupyter_client=8.6.3=py310h06a4308_0
  - jupyter_core=5.7.2=py310h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py310h06a4308_0
  - openssl=3.0.15=h5eee18b_0
  - packaging=24.2=py310h06a4308_0
  - parso=0.8.4=py310h06a4308_0
  - pip=25.0=py310h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - python=3.10.16=he870216_1
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.2=py310h5eee18b_0
  - traitlets=5.14.3=py310h06a4308_0
  - typing_extensions=4.12.2=py310h06a4308_0
  - wheel=0.45.1=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==1.4.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.12
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.8.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - astunparse==1.6.3
      - async-lru==2.0.4
      - async-timeout==5.0.1
      - attrs==25.1.0
      - audioread==3.0.1
      - babel==2.17.0
      - backoff==2.2.1
      - backports-tarfile==1.2.0
      - beautifulsoup4==4.13.3
      - bleach==6.2.0
      - boto3==1.36.14
      - botocore==1.36.14
      - bottle==0.13.2
      - build==1.2.2.post1
      - cachecontrol==0.14.2
      - cachetools==5.5.1
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - cleo==2.1.0
      - click==8.1.8
      - comm==0.2.2
      - contextlib2==21.6.0
      - contourpy==1.3.1
      - crashtest==0.4.1
      - cryptography==44.0.1
      - cycler==0.12.1
      - db-dtypes==1.4.1
      - debugpy==1.8.12
      - defusedxml==0.7.1
      - distlib==0.3.9
      - docker==7.1.0
      - dulwich==0.22.7
      - etils==1.12.0
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fastapi==0.115.8
      - fastjsonschema==2.21.1
      - ffmpy==0.5.0
      - filelock==3.17.0
      - findpython==0.6.2
      - fire==0.7.0
      - flatbuffers==25.2.10
      - fonttools==4.55.8
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2025.2.0
      - gast==0.6.0
      - gcsfs==2025.2.0
      - google-api-core==2.24.1
      - google-auth==2.38.0
      - google-auth-oauthlib==1.2.1
      - google-cloud-bigquery==3.29.0
      - google-cloud-core==2.4.2rc0
      - google-cloud-storage==3.0.0
      - google-crc32c==1.6.0
      - google-pasta==0.2.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.67.0
      - gradio==5.16.1
      - gradio-client==1.7.0
      - grpcio==1.70.0
      - grpcio-status==1.63.0rc1
      - h11==0.14.0
      - h5py==3.13.0
      - httpcore==1.0.7
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.29.1
      - idna==3.10
      - imageio==2.37.0
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - installer==0.7.0
      - ipykernel==6.26.0
      - ipython==8.17.2
      - ipywidgets==8.1.1
      - isoduration==20.11.0
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.1.0
      - jeepney==0.8.0
      - jinja2==3.1.5
      - jmespath==1.0.1
      - joblib==1.4.2
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - keras==3.8.0
      - keras-tuner==1.4.7
      - keyring==25.6.0
      - kiwisolver==1.4.8
      - kt-legacy==1.0.5
      - lazy-loader==0.4
      - libclang==18.1.1
      - librosa==0.10.2.post1
      - lightning==2.5.0.post0
      - lightning-cloud==0.5.70
      - lightning-sdk==2025.7.22
      - lightning-utilities==0.12.0
      - litdata==0.2.32
      - litserve==0.2.6
      - llvmlite==0.44.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.8.2
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.1.1
      - ml-collections==0.1.1
      - ml-dtypes==0.4.1
      - more-itertools==10.6.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - namex==0.0.8
      - narwhals==1.27.1
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.4.2
      - notebook==7.3.2
      - notebook-shim==0.2.4
      - numba==0.61.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.8.61
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - opt-einsum==3.4.0
      - optree==0.14.0
      - orjson==3.10.15
      - overrides==7.7.0
      - pandas==2.1.4
      - pandas-gbq==0.27.0
      - pandocfilters==1.5.1
      - pbs-installer==2025.2.12
      - perch-hoplite==0.1.0
      - pexpect==4.9.0
      - pillow==11.1.0
      - pkginfo==1.12.1.2
      - platformdirs==4.3.6
      - plotly==6.0.0
      - poetry==2.1.1
      - poetry-core==2.1.1
      - pooch==1.8.2
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - propcache==0.2.1
      - proto-plus==1.26.0
      - protobuf==4.23.4
      - proxy-tools==0.1.0
      - psutil==6.1.1
      - pure-eval==0.2.3
      - pyarrow==19.0.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydata-google-auth==1.9.1
      - pydub==0.25.1
      - pygments==2.19.1
      - pyjwt==2.10.1
      - pyparsing==3.2.1
      - pyproject-hooks==1.2.0
      - python-dotenv==1.0.1
      - python-json-logger==3.2.1
      - python-multipart==0.0.20
      - pytorch-lightning==2.5.0.post0
      - pytz==2025.1
      - pywebview==5.4
      - pyyaml==6.0.2
      - pyzmq==26.2.1
      - rapidfuzz==3.12.1
      - referencing==0.36.2
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - resampy==0.4.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rpds-py==0.22.3
      - rsa==4.9
      - ruff==0.9.7
      - s3transfer==0.11.2
      - safehttpx==0.1.6
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - secretstorage==3.3.3
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - shellingham==1.5.4
      - simple-term-menu==1.6.6
      - simsimd==6.2.1
      - six==1.17.0
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soupsieve==2.6
      - soxr==0.5.0.post1
      - stack-data==0.6.3
      - starlette==0.45.3
      - sympy==1.13.3
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.18.0
      - tensorflow-estimator==2.15.0
      - tensorflow-hub==0.16.1
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.5.0
      - terminado==0.18.1
      - tf-keras==2.18.0
      - threadpoolctl==3.5.0
      - tinycss2==1.4.0
      - tomli==2.2.1
      - tomlkit==0.13.2
      - torch==2.2.1+cu121
      - torchmetrics==1.3.1
      - torchvision==0.17.1+cu121
      - tqdm==4.67.1
      - triton==2.2.0
      - trove-classifiers==2025.2.18.16
      - typer==0.15.1
      - types-python-dateutil==2.9.0.20241206
      - tzdata==2025.1
      - uri-template==1.3.0
      - urllib3==2.3.0
      - usearch==2.16.9
      - uvicorn==0.34.0
      - uvloop==0.21.0
      - virtualenv==20.29.2
      - watchfiles==1.0.4
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==14.2
      - werkzeug==3.1.3
      - wget==3.2
      - widgetsnbextension==4.0.13
      - wrapt==1.14.1
      - yarl==1.18.3
      - zipp==3.21.0
      - zstandard==0.23.0
prefix: /home/zeus/miniconda3/envs/cloudspace
